package com.entity;
// Generated Mar 29, 2017 1:12:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Person2 generated by hbm2java
 */
@Entity
@Table(name="person2"
    ,catalog="testShibo"
    , uniqueConstraints = @UniqueConstraint(columnNames="credit") 
)
public class Person2  implements java.io.Serializable {


     private int id;
     private Date birthdate;
     private String credit;
     private String email;
     private String name;
     private String password;

    public Person2() {
    }

    public Person2(int id, Date birthdate, String credit, String email, String name, String password) {
       this.id = id;
       this.birthdate = birthdate;
       this.credit = credit;
       this.email = email;
       this.name = name;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", nullable=false, length=0)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="credit", unique=true, nullable=false, length=45)
    public String getCredit() {
        return this.credit;
    }
    
    public void setCredit(String credit) {
        this.credit = credit;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


